name: CI

on:
  # push:
  # branches: [ main ]
  pull_request:
    branches: [main]
  workflow_dispatch:
  push:
    branches: [main]
    tags:
      - v*

jobs:
  release-operator:
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-latest
    env:
      IMG: ghcr.io/drschlaubi/operator:${{ github.ref_name }}
      VERSION: ${{ github.ref_name }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Build
        run: |
          make build

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Github container repository
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install helm
        uses: azure/setup-helm@v4

      - name: Build and Publish image into GHCR
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/drschlaubi/operator:${{ github.ref_name }}
          platforms: |
            linux/amd64
            linux/arm64
        env:
          DOCKER_BUILDKIT: 1
          DOCKER_USERNAME: ${{ github.actor }}
          DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

      - name: publish github release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./bin/dragonfly-operator
            LICENSE
          name: ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          body: |
            Release ${{ github.ref_name }}

            Docker image: ghcr.io/drschlaubi/operator:${{ github.ref_name }}
            Helm chart: oci://ghcr.io/drschlaubi/dragonfly-operator/helm
          draft: true
